services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - web

  website:
    image: ghcr.io/davidklouis-sketch/xyra-ai-finished/website:main
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      # HTTPS Router
      - "traefik.http.routers.website.rule=Host(`${DOMAIN:-xyra.digital}`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.routers.website.tls.certresolver=letsencrypt"
      - "traefik.http.services.website.loadbalancer.server.port=80"
      # HTTP to HTTPS Redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.website-http.rule=Host(`${DOMAIN:-xyra.digital}`)"
      - "traefik.http.routers.website-http.entrypoints=web"
      - "traefik.http.routers.website-http.middlewares=redirect-to-https"
    networks:
      - web

networks:
  web:
    driver: bridge
