services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - web

  website:
    image: ghcr.io/davidklouis-sketch/xyra-ai-finished/website:main
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      # Service
      - "traefik.http.services.website.loadbalancer.server.port=80"
      # HTTP to HTTPS Redirect Middleware (except for ACME challenges)
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # Redirect xyra.digital to xyra-ai.de
      - "traefik.http.middlewares.redirect-xyra-digital.redirectregex.regex=^https?://(www\\.)?xyra\\.digital(.*)"
      - "traefik.http.middlewares.redirect-xyra-digital.redirectregex.replacement=https://xyra-ai.de$$2"
      - "traefik.http.middlewares.redirect-xyra-digital.redirectregex.permanent=true"

      # xyra.digital - HTTPS (Redirect to xyra-ai.de)
      - "traefik.http.routers.website-xyra-digital.rule=Host(`xyra.digital`)"
      - "traefik.http.routers.website-xyra-digital.entrypoints=websecure"
      - "traefik.http.routers.website-xyra-digital.tls=true"
      - "traefik.http.routers.website-xyra-digital.tls.certresolver=letsencrypt"
      - "traefik.http.routers.website-xyra-digital.service=website"
      - "traefik.http.routers.website-xyra-digital.middlewares=redirect-xyra-digital"
      # xyra.digital - HTTP (Redirect to xyra-ai.de)
      - "traefik.http.routers.website-xyra-digital-http.rule=Host(`xyra.digital`)"
      - "traefik.http.routers.website-xyra-digital-http.entrypoints=web"
      - "traefik.http.routers.website-xyra-digital-http.service=website"
      - "traefik.http.routers.website-xyra-digital-http.middlewares=redirect-xyra-digital"

      # www.xyra.digital - HTTPS (Redirect to xyra-ai.de)
      - "traefik.http.routers.website-www-xyra-digital.rule=Host(`www.xyra.digital`)"
      - "traefik.http.routers.website-www-xyra-digital.entrypoints=websecure"
      - "traefik.http.routers.website-www-xyra-digital.tls=true"
      - "traefik.http.routers.website-www-xyra-digital.tls.certresolver=letsencrypt"
      - "traefik.http.routers.website-www-xyra-digital.service=website"
      - "traefik.http.routers.website-www-xyra-digital.middlewares=redirect-xyra-digital"
      # www.xyra.digital - HTTP (Redirect to xyra-ai.de)
      - "traefik.http.routers.website-www-xyra-digital-http.rule=Host(`www.xyra.digital`)"
      - "traefik.http.routers.website-www-xyra-digital-http.entrypoints=web"
      - "traefik.http.routers.website-www-xyra-digital-http.service=website"
      - "traefik.http.routers.website-www-xyra-digital-http.middlewares=redirect-xyra-digital"

      # xyra-ai.de - HTTPS
      - "traefik.http.routers.website-xyra-ai-de.rule=Host(`xyra-ai.de`)"
      - "traefik.http.routers.website-xyra-ai-de.entrypoints=websecure"
      - "traefik.http.routers.website-xyra-ai-de.tls=true"
      - "traefik.http.routers.website-xyra-ai-de.tls.certresolver=letsencrypt"
      - "traefik.http.routers.website-xyra-ai-de.service=website"
      # xyra-ai.de - HTTP Redirect
      - "traefik.http.routers.website-xyra-ai-de-http.rule=Host(`xyra-ai.de`)"
      - "traefik.http.routers.website-xyra-ai-de-http.entrypoints=web"
      - "traefik.http.routers.website-xyra-ai-de-http.service=website"
      - "traefik.http.routers.website-xyra-ai-de-http.middlewares=redirect-to-https"

      # www.xyra-ai.de - HTTPS
      - "traefik.http.routers.website-www-xyra-ai-de.rule=Host(`www.xyra-ai.de`)"
      - "traefik.http.routers.website-www-xyra-ai-de.entrypoints=websecure"
      - "traefik.http.routers.website-www-xyra-ai-de.tls=true"
      - "traefik.http.routers.website-www-xyra-ai-de.tls.certresolver=letsencrypt"
      - "traefik.http.routers.website-www-xyra-ai-de.service=website"
      # www.xyra-ai.de - HTTP Redirect
      - "traefik.http.routers.website-www-xyra-ai-de-http.rule=Host(`www.xyra-ai.de`)"
      - "traefik.http.routers.website-www-xyra-ai-de-http.entrypoints=web"
      - "traefik.http.routers.website-www-xyra-ai-de-http.service=website"
      - "traefik.http.routers.website-www-xyra-ai-de-http.middlewares=redirect-to-https"
    networks:
      - web

networks:
  web:
    driver: bridge
